(deftheme mustafa
  "Created 2021-01-14.")

(custom-theme-set-faces
 'mustafa
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#7da6ff"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#32344a"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#acb0d0"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#acb0d0"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#32344a"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ff9e64"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold ((class color) (min-colors 89)) :foreground "#ad8ee6"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#9ece6a"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#0db9d7"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#e0af68"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff7a93" :background "#2c2d37"))))
 '(region ((((class color) (min-colors 89)) (:background "#a9b1d6" :foreground "#1a1b26"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#8e95b4" :background "#3f3f49"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2c2d37" :foreground "#8087a3"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#3f3f49"))))
 '(isearch ((((class color) (min-colors 89)) (:bold t :foreground "#ff7a93" :background "#3f3f49"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil) :bold t :foreground "#8087a3" :background "#2c2d37"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil :style pressed-button) :foreground "#e0af68" :background "#1a1b26" :weight normal))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:bold t :foreground "#ff9e64" :background nil))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#ad8ee6" :box nil :weight bold))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#a9b1d6"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#8e95b4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:bold t :foreground "#ad8ee6"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#acb0d0" :underline t))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ff7a93"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#ff7a93")))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#9ba3c5" :background "#3f3f49"))))
 '(line-number ((t (:inherit fringe))))
 '(line-number-current-line ((t (:inherit fringe :foreground "white" :weight bold))))
 '(default ((t (:foreground "#a9b1d6"))))
 '(company-tooltip-selection ((t (:background "#444b6a" :foreground "#b9f27c"))))
 '(company-tooltip ((t (:background "#32344a" :foreground "#acb0d0"))))
 '(lsp-ui-doc-background ((t (:background "#1a1b26")))))

(provide-theme 'mustafa)
